### ISSUE TITLE
Poker Engine

### ISSUE THREAD

**Issue by shtefcs** [mdp/JsPoker#19]
Hi there,

Can this code be used as poker engine for real human multiplayer game ? I know this is made for bots, but I wonder is poker logic is there ? 

My idea is to add GUI and let real people play. 

Stefan

**Comment by mdp** [comment]
Yep, it's basically just the engine with some bot logic laid on top. It's async, so it's not really a problem to extract out the player bot code to just accept input from a real person. Let me know if you run into any problems.

**Comment by shtefcs** [comment]
Tnx for replay. Are u interested to freelance on this project ?
